version: "3.9"
services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev